### ISSUE TITLE
Sometimes the login will hang and not go through

### ISSUE THREAD

**Issue by wezlol** [EinBaum/AutoLogin#1]
- Loading box stays empty: https://i.imgur.com/F99ZpXt.png
- Stays on Connecting

Perhaps the script goes too fast.

**Comment by EinBaum** [comment]
True, it enters the login info too fast and it's unpredictable. I've added a delay option:

AutoLogin.exe GAMEPATH ACCOUNT PASSWORD DELAY_MS

where DELAY_MS is a number in milliseconds, e.g. 1000
Does it work for you now?
